### ISSUE TITLE
Show/Hide Sidebar doesn't work properly

### ISSUE THREAD

**Issue by ZenonBrak** [synappser/FinderFix#10]
Show/Hide Sidebar doesn't work properly and it causes Sidebar to disappear completely without option to Show/Hide it as this option gets greyed out in View menu.

**Comment by synappser** [comment]
Hi @ZenonBrak and thank you for reporting this issue. I also noticed this weird behaviour of Finder where the Toolbar needs to be showing to get the Sidebar to show. I'm still investigating the correct approach and the solution could be to have the Toolbar checkbox automatically checked if the Sidebar one is checked. I'll keep you posted.

**Comment by jmorais** [comment]
@synappser is there a way to quick revert to the old version? It kinda broke everything here.

**Comment by synappser** [comment]
@jmorais, sorry but there's no way back to the old version, but I can help you find your way in the new one if you could be more explicit.

**Comment by jmorais** [comment]
@synappser The show/hide sidebar isn't working (it's always hiding and I can't toggle on the Finder menu if FinderFix is running)

**Comment by synappser** [comment]
Push the "Relaunch Finder" button at the bottom of the View pane. You might also need to close the recalcitrant window and reopen it anew.

- Is "Automatically remove .DS_Store files" checked?
- If you open your Documents window or Applications folder, does it behave the same?

**Comment by jmorais** [comment]
I tried to Relaunch Finder a bunch of times but it did not work. I had to first uncheck toolbar+sidebar -> restart -> check both -> restart again and then it finally worked.

* "Automatically remove .DS_Store files" was checked
* Any folder was behaving this way (Documents, Applications, External drives, Trash)

**Comment by bankm1** [comment]
I have the same problem with the current version. Everything is hidden in finder windows with finderfix active. Side bar, tool bar, path bar all missing. Quit finderfix & they all reappear.

**Comment by synappser** [comment]
@ZenonBrak, @jmorais, @bankm1, I heard you :smile:. Please hold on while I prepare a new release where you can switch the View settings pane off if you wish to disable enforcing its rules. Meanwhile, check the Sidebar and Toolbar only in pair.

**Comment by jmorais** [comment]
Goes to show how much you work is important to our daily lives! Really appreciate it.

Also, checking both sidebar and toolbar seems to do the trick just fine!

**Comment by synappser** [comment]
@ZenonBrak, @jmorais, @bankm1, I pushed a new release [FinderFix v0.7.2b](https://github.com/synappser/FinderFix/releases) that specifically addresses the Sidebar issue you were facing. If all goes well, I will later announce it on the [Downloads](https://synappser.github.io/downloads/) page. Thank you.
