### ISSUE TITLE
Code-Signing & Notarizing the App

### ISSUE THREAD

**Issue by SENTINELITE** [synappser/FinderFix#17]
What's the blocker for code-signing & Notarization of the app? Are you planning on doing those things when 1.0 releases?

The average user isn't going to jump through multiple security "vulnerability" dialogs & accept them...

I consider myself pretty technically knowledgable, & find this a little off-guard, especially the pseudonym "ed77..." paragraph in installer.

**Comment by synappser** [comment]
@SENTINELITE For more context, please read this post on HN:
https://news.ycombinator.com/item?id=31763451
