### ISSUE TITLE
Nothing visible running

### ISSUE THREAD

**Issue by kdawson** [synappser/FinderFix#18]
I installed 0.7.2 on Monterey 12.6.6; went through all the hoops and apparently it started. Activity Monitor lists it and it appears in Login Items in System Prefs. But I can't see any way to interact with the app. Neither the Dock nor cmd-tab shows anything related to FinderFix. Is there some secret way of getting to a Settings window?

**Comment by synappser** [comment]
Taskan is a menu bar app with an easily recognisable icon (4 diverging arrows). If you are using a menu bar manager such as Bartender, it might get hidden at first launch. By clicking on the menu bar icon, you have access to its Preferences pane where you can activate it.
