### ISSUE TITLE
What's with ⌘-C / ⌘-V?

### ISSUE THREAD

**Issue by kdawson** [synappser/FinderFix#19]
Could you please explain what this feature does? As far as I know, since 1984 Copy & Paste have been ⌘-C & ⌘-V. What does FinderFix do that is different?

**Comment by synappser** [comment]
@kdawson It's mainly about consistency and muscle memory when you're coming from Linux or Windows. Compared to using Option+Command+V, Cut & Paste also makes more sense than Copy & Move.
