### ISSUE TITLE
FinderFix_v0.7.3b expired

### ISSUE THREAD

**Issue by nodeam** [synappser/FinderFix#21]
MacStudio M2 Max (arm), Sonoma 14..4.1 
Working great!

Any chance to get a new beta or a final, if completed?

**Comment by synappser** [comment]
Please download [v0.7.4b](https://github.com/synappser/FinderFix/releases/download/v0.7.4/FinderFix_v0.7.4b.dmg), released May 5.

Thank you.

**Comment by nodeam** [comment]
Thanx
