### ISSUE TITLE
FinderFix beta expired 0.7.4

### ISSUE THREAD

**Issue by Nemesis19** [synappser/FinderFix#22]
Dear Dev,

I love FinderFix, the latest beta has expired but I'd like to understand what's keeping you from releasing the final release.

Let me know if I can help cause it's working perfectly so I don't think it can stay in Beta forever, it's more than ready to be final.

Thanks

**Comment by synappser** [comment]
Dear Fabrizio,

Thank you for your kind words about FinderFix. Version 0.7.3b has indeed expired but you can download [v0.7.4b](https://github.com/synappser/FinderFix/releases/download/v0.7.4/FinderFix_v0.7.4b.dmg), released May 5, to keep testing it.

Please understand that a beta can serve several purposes. The first of which is obviously to test the project's feasibility and assess the general interest in it. This goal is now fulfilled and I am heartened by how well FinderFix was received. However, there's still a lot to be done before it is ready for prime time. There's room for more features and it needs some refactoring before I can call it a final.

What's more, while the software might be ready, I am not. I'm still stuck with some time consuming administrative formalities that come with the retirement and this might take yet another year to be completed. I take software development to heart and I want to properly conclude all the current paperwork before I fully tackle final software releases of FinderFix and my other applications (several new ones are planned).

I will meanwhile, keep releasing more beta versions with small improvements.

Thank you for your patience.

**Comment by Nemesis19** [comment]
I see, thanks for the new beta release! keep up with the good work and best wishes for everything else!
