### ISSUE TITLE
Operational windows excluded from Finder Fix control

### ISSUE THREAD

**Issue by Nemesis19** [synappser/FinderFix#3]
Dear developer,

finder fix is simple and awesome. Coming from finderminder and finally  I've found something updated!

I'd like to suggest to exclude from alignment the operations windows like those with progress bar when you paste a file somewhere in a folder.

I remember Finderminder never tackled those windows but seeing them on my top-left corners of my Finder windows is becoming annoying 😓 

Thanks for your effort

**Comment by synappser** [comment]
Hi @Nemesis19,

Thank you for the compliment. FinderFix currently excludes the following windows - File Info, Quick Look, Connect to Server. If I can distinctively identify those "operations widows" during run time, they will be added to the excluded files list.

Stay tuned, and thank you for adopting FinderFix.

**Comment by synappser** [comment]
FinderFix [v0.6.7b](https://github.com/synappser/FinderFix/releases/tag/v0.6.7) excludes operation windows from FinderFix's control.

**Comment by Nemesis19** [comment]
tested, working like a charm!
