### ISSUE TITLE
Narrower Finder Windows

### ISSUE THREAD

**Issue by Sam2564711** [synappser/FinderFix#7]
**Is your feature request related to a problem? Please describe.**
Because of our office workflow we need to have several finder windows open at the same time. One for incoming files from each user and one for outgoing files after they have been reviewed. When you have several windows open you do not have screen space for running applications.

**Describe the solution you'd like**
We would like a window just wide enough to show the small icon and a short file name(maybe a minimum width of 120, current minimum in FinderFix is 460). This was possible in Mac Os 10.6.8 but the window width doubled in later systems.

**Describe alternatives you've considered**
The only option we have found is piling window on top of each other which slows the workflow and has caused some files to miss the review process. 

**Additional context**

**Comment by synappser** [comment]
Thank you for your feature request @Sam2564711. I'm however afraid the smallest you can get with each of the Sidebar, Toolbar, Tab Bar, Path Bar, and Status Bar hidden is 316 w x 300 h (291 by cheating with the menu bar). I'll reduce the minimum allowed to those dimensions with an upcoming release.

Dimensions beyond these would require messing with kernel extensions and disabling the System Integrity Protection (SIP).

**Comment by synappser** [comment]
Enhancement implemented in release [v0.7.1](https://github.com/synappser/FinderFix/releases/tag/v0.7.1).
