### ISSUE TITLE
View options 

### ISSUE THREAD

**Issue by eks28** [synappser/FinderFix#8]
v0.7.1b 

a toggle to disable view otions cause i like em of but adds side bar to disk image windows when i open them

so if you could ad that would be great cause some time i dont want to disable/or enable different view options

**Comment by eks28** [comment]
sorry confusing to convey

**Comment by synappser** [comment]
@eks28, It's not confusing at all. On the contrary, it makes perfect sense.

You're right that FinderFix should allow you to choose between overriding or not the regular behaviour.

Anyway, it was planned as you can see it in the Roadmap (Override system view settings with own settings) and I'll be adding an override switch with the next release. Thanks for confirming it's needed.

**Comment by synappser** [comment]
@eks28, I pushed a new release [FinderFix v0.7.2b](https://github.com/synappser/FinderFix/releases) that specifically addresses the Sidebar issue you were facing. If all goes well, I will later announce it on the [Downloads](https://synappser.github.io/downloads/) page. Thank you.
